# Generated by Django 2.1.2 on 2018-10-27 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Diary',
        ),
        migrations.AlterModelOptions(
            name='diary',
            options={'verbose_name': '日記', 'verbose_name_plural': '日記'},
        ),
    ]
